### ISSUE TITLE
I would like some help getting this to work

### ISSUE THREAD

**Issue by RandyLov** [linrock/chess-puzzle-maker#1]
when i issue the command make_puzzles.py --pgn games.pgn the file make_puzzles.py opens up in notepad  thanks for any hep

**Comment by RandyLov** [comment]
this is my output now

Traceback (most recent call last):
  File "C:\Users\Randy\Desktop\puzzlemaker\make_puzzles.py", line 10, in <module>
    from chess import Board
  File "C:\Users\Randy\Desktop\puzzlemaker\chess\__init__.py", line 57
    "R": u"\u2656", "r": u"\u265c",
              ^
SyntaxError: invalid syntax
