### ISSUE TITLE
Problem in code with the latest version of stockfish

### ISSUE THREAD

**Issue by tornado1785** [linrock/chess-puzzle-maker#5]
Hi , i am trying very hard but your python code doesnt work. this Happens when i run bulid_stockfish.sh file
"Getting latest Stockfish ...
build-stockfish.sh: git: command not found
- Determining CPU architecture ...
- Building and profiling stockfish-x86_64 ... (patience advised)
build-stockfish.sh: Stockfish/src: No such file or directory
C:\SHELL~1.W32\make.exe: *** No rule to make target `profile-build'.  Stop.
- Done!"
please upload a video on youttube on how to use this puzzel generater because everyone cant follow coding instruction properly

**Comment by tornado1785** [comment]
This is what happens after it analysis the pgn

Traceback (most recent call last):
  File "F:\Chess\chess-puzzle-maker-master\chess-puzzle-maker-master\make_puzzles.py", line 120, in <module>
    puzzles = find_puzzle_candidates(game, scan_depth=settings.scan_depth)
  File "F:\Chess\chess-puzzle-maker-master\chess-puzzle-maker-master\puzzlemaker\puzzle_finder.py", line 26, in find_puzzle_candidates
    cur_score = AnalysisEngine.best_move(next_board, scan_depth).score
  File "F:\Chess\chess-puzzle-maker-master\chess-puzzle-maker-master\puzzlemaker\analysis.py", line 49, in best_move
    return AnalyzedMove(best_move, board.san(best_move), score)
  File "C:\Users\hp\miniconda3\lib\site-packages\chess\__init__.py", line 2655, in san
    return self._algebraic(move)
  File "C:\Users\hp\miniconda3\lib\site-packages\chess\__init__.py", line 2668, in _algebraic
    san = self._algebraic_and_push(move, long=long)
  File "C:\Users\hp\miniconda3\lib\site-packages\chess\__init__.py", line 2676, in _algebraic_and_push
    self.push(move)
  File "C:\Users\hp\miniconda3\lib\site-packages\chess\__init__.py", line 2015, in push
    move = self._to_chess960(move)
  File "C:\Users\hp\miniconda3\lib\site-packages\chess\__init__.py", line 3413, in _to_chess960
    if move.from_square == E1 and self.kings & BB_E1:
AttributeError: 'NoneType' object has no attribute 'from_square'
